/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControladoresVistas;

import Modelos.Circulo;
import Modelos.Cuadrado;
import Modelos.Imagen;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author pipet
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
//        Cuadrado cuadrado1= new Cuadrado(10, 10, Color.black, Color.red, 90);
//        Circulo circulo1=new Circulo(100, 10, Color.blue, Color.green, 70);
//        Imagen elHongo=new Imagen(10, 100, "src/Imagenes/hongo.png", 64, 64);
//        this.lienzo1.getFiguras().add(cuadrado1);
//        this.lienzo1.getFiguras().add(circulo1);
//        this.lienzo1.getFiguras().add(elHongo);
        int numerosParaMatriz[][] = {{1,1,2,2,2,2,2,1,1,3,3,3,3,0,0,0},
                                     {1,1,4,4,2,4,2,3,3,3,5,3,3,3,0,0},
                                     {0,1,2,2,4,4,2,1,1,1,3,3,3,3,6,6},
                                     {0,1,0,2,2,4,0,1,1,1,1,2,3,3,6,6},
                                     {0,1,0,2,2,4,0,0,1,1,2,2,2,0,6,6},
                                     {0,0,0,0,2,0,0,0,0,1,2,2,2,0,0,6},
                                     {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                                     {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};                      
       
        int f = 0;  
        int cantidad = 0; 
        Color relleno = Color.white; 
        
        for (int j = 240; j < 481; j=j+30) 
        {   
            int c = 0; 
            if(f < 8)
            {
                for (int i = 0; i < 481; i=i+30) 
                {
                    if(c < 16)
                    {
                        if(numerosParaMatriz[f][c]==1)
                        {
                            relleno = Color.red; 
                        }else if(numerosParaMatriz[f][c]==2)
                        {
                            relleno = Color.orange; 
                        }else if(numerosParaMatriz[f][c]==3)
                        {
                            relleno = Color.blue;
                        }else if(numerosParaMatriz[f][c]==4)
                        {
                            relleno = Color.black;
                        }else if(numerosParaMatriz[f][c]==5)
                        {
                            relleno = Color.yellow;
                        }else if(numerosParaMatriz[f][c]==6)
                        {
                            relleno = Color.darkGray;
                        }else 
                        {
                            relleno = Color.white;
                        }
                        
                         Cuadrado c1 = new Cuadrado(j, i, Color.black, relleno,30);
                        this.lienzo1.getFiguras().add(c1);
                        c++;
                    }
                }
                
                f++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new ControladoresVistas.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ControladoresVistas.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
